### PR TITLE
updating or adding new ctp rules

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

# Description

I'm adding updates from CTP, also bumping license headers and adding spell checking.

Related issues: #200

### CODE REVIEW

**Comment by vsoch** [comment]
@howff let me know if you will have time to review!

**Comment by glebsts** [comment]
thank you Vanessa, I accidentally saw this PR and now I know `codespell` exists, and I just integrated it into CI at work :)

**Comment by howff** [comment]
Looks good to me, thank you very much!

**Comment by vsoch** [comment]
https://pypi.org/project/deid/0.2.29/

**Pull request merged**
