### PR TITLE
fix import from pydicom.tagtools to pydicom.tag

### PR DESCRIPTION
**Pull request by BrianKolowitz**

### CODE REVIEW

**Comment by BrianKolowitz** [comment]
fix

**Comment by vsoch** [comment]
hey @BrianKolowitz  - this PR looks good - I think for the continuous integration we need to update the version of pydicom used here --> https://github.com/pydicom/deid/blob/master/.travis.yml#L14 

I had specified it to that version explicitly because of maintaining the old version, but with this fix we should be good :)

**Comment by BrianKolowitz** [comment]
I modified the .travis.yml to include the latest hash which makes the build pass. 
```
- pip install git+git://github.com/pydicom/pydicom.git@4ddd9a70000ec72a53ea2dab8bc8063043691548
```

**Comment by vsoch** [comment]
Awesome! Huge thanks for doing this. I'm going to be opening up the development branch proper with a CHANGELOG, but these tweaks can go right into master for now. Merging!

**Comment by vsoch** [comment]
Do you know why it shows the commits that I made from the (now merged) PR? I want to make sure I didn't muck something up with git - if those are in master the comparison shouldn't show them here.

**Comment by BrianKolowitz** [comment]
I have to admit I'm not an expert in open source collaboration. I believe it kept tracking my commits along the way. I probably should have created a separate branch and opened the pull request from there. 

If you'd like to reject these changes I can create a clean pull request.

**Comment by vsoch** [comment]
Ah, not necessary! Let's see what happens when I just merge, it should arguably show the same commits.

**Comment by vsoch** [comment]
The code looks good! A few months back I think Github changed to a container based framework to run github pages and the site generally, so I'd bet they tweaked some algorithm that would update the code, etc. to re-test or re-compare against changed bases. In this case it's probably a bug, but I haven't seen it before so it's likely a one time thing. Anyway, thank you again! If you have other ideas for deid, please open an issue and we can chat about it. There aren't a ton of options out there for this task, and especially with python. I am hoping to (eventually) write a small paper on it, and you are welcome to be a part of that too!

**Pull request merged**
