### PR TITLE
Add codespell to CI to catch typos early

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
# Description

Run [codespell](https://github.com/codespell-project/codespell) in CI to catch typos early on.

Use GitHub Actiosn with [actions-codespell](https://github.com/codespell-project/actions-codespell).

Related PR: #185

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] My code follows the style guidelines of this project

### CODE REVIEW

**Comment by vsoch** [comment]
Good idea! Please use an exact sha instead of a branch or tag so it's not a moving target.

**Comment by DimitriPapadopoulos** [comment]
For what it's worth, it's supposed to be used like this:
```
uses: codespell-project/actions-codespell@master
```
See https://github.com/codespell-project/actions-codespell#usage

**Comment by DimitriPapadopoulos** [comment]
But I agree there is a risk.

**Comment by vsoch** [comment]
Yes I'm aware how GitHub actions work - for actions that I don't control my preference is to use a non moving target. A commit sha, and not a branch or release tag.

**Comment by DimitriPapadopoulos** [comment]
OK, I have used the current commit.

**Comment by vsoch** [comment]
Perfect! I think you just need to provide the entire sha and it will work.

**Comment by vsoch** [comment]
Thanks! This will prevent my future misspellings :)

**Comment by DimitriPapadopoulos** [comment]
In the future, false positives can be added to **`.github/codespell_ignore_words.txt`**. Hopefully there won't be many.

**Pull request merged**
