### PR TITLE
finishing tweaks to docstrings

### PR DESCRIPTION
**Pull request by vsoch**
This will address the issue of having the MediaInstanceSOPUId (or something along those lines!) in the file_meta header (group 0002) which can be used to identify the unique machine. This will close https://github.com/pydicom/deid/issues/72.

@Biggz1313 would you care to test? You should first uninstall all versions of deid, do this until it tells you it's not installed:

```bash
pip uninstall deid
```

Then clone this branch, and install

```bash
git clone -b fix/preamble https://www.github.com/pydicom/deid
cd deid
python setup.py install
```

And make sure to target the python executable you are using!

### CODE REVIEW

**Comment by vsoch** [comment]
I need to be working on other things for a but, but will be back later to see if you've had a chance to test it out. Definitely no rush!

**Comment by Biggz1313** [comment]
Ahh, yes you did ask me to test that.  I've opened in 2 viewers and they open just fine.

**Comment by vsoch** [comment]
okay great! Apologies for the delay - you caught me just as I was jumping between things. Let's get this released soon.

**Comment by vsoch** [comment]
Released https://pypi.org/project/deid/0.1.19/

**Pull request merged**
