### PR TITLE
Add/sequence replacement

### PR DESCRIPTION
**Pull request by vsoch**
# Description

Related issues: #102 

This will allow for REPLACE and BLANK to work for nested sequences.  I've included a full example in the docs, and linked to an example folder in the repository.

### CODE REVIEW

**Comment by vsoch** [comment]
Here you go @danielsnider, there is a full example added in the docs and examples folder. This will cover `REPLACE` and `BLANK` since we can easily dig into the nested structure and edit it (and thanks to Python objects the parent also gets the changes) but I didn't see an easy way to remove an item from a sequence, or ADD. If someone else wants these in the future, they can complain about it and PR. :)

**Comment by danielsnider** [comment]
I'm going to test it right meow! <3

**Comment by danielsnider** [comment]
Works like a charm! I'm reviewing the code some more too. 👍

Thanks so much. If you're ever in Toronto I'll see to it that your treated like royalty.

**Comment by vsoch** [comment]
Haha, nice!

While you’re reviewing, if you have ideas for how we could also support commands to add or remove content, this could be desired say day. I tried the traditional del varname to see if it might, for example, remove a DataElement from a sequence, but it didn’t work. The only way would be to loop through the sequence, and then not add an element to some new sequence. But then we would have to keep the parent as well to link to it.

Is it worth trying, or save for some future user to ask about?

**Comment by danielsnider** [comment]
I would say fix it when truly needed 👍

**Comment by vsoch** [comment]
Sounds good. Let me know when you've finished your review and I'll release.

**Comment by danielsnider** [comment]
Will do!

**Comment by danielsnider** [comment]
Approved 👍. I learned a lot from reading your code. I don't have any more suggestions, sorry!

**Comment by vsoch** [comment]
No worries! I just pushed a fix for the typo in the docs. When this passes, I'll merge and then release on pypi (and then after that, it gets PRd --> released on conda too!)

**Comment by vsoch** [comment]
Always a pleasure @danielsnider !

https://pypi.org/project/deid/0.1.34/

**Comment by danielsnider** [comment]
Huge thanks @vsoch !

**Pull request merged**
