### PR TITLE
Example create dicom spreadsheet

### PR DESCRIPTION
**Pull request by BrianKolowitz**
Need an easy way to for a person to validate their deidentification worked. This example 1st scans a directory and creates a unique set of dicom tags across all files. It then reads the values for all tags in all files and creates a csv file which can be loaded into excel or a database to review.

### CODE REVIEW

**Comment by vsoch** [comment]
This will be very useful! Would you be able to write a page to include with the docs for how to use it, then I'll use that to test (and future users will both know about and have instructions for doing this?)

**Comment by vsoch** [comment]
This looks good! @BrianKolowitz ready for merge?

**Comment by BrianKolowitz** [comment]
@vsoch sure, do i need to do something?

**Comment by vsoch** [comment]
Haha nope, just give me the A-OK :)

**Comment by BrianKolowitz** [comment]
@vsoch good to go.

**Comment by vsoch** [comment]
Merged, thank you for the example!

**Pull request merged**
