### PR TITLE
Fix/filter exception

### PR DESCRIPTION
**Pull request by wetzelj**
# Description

Related issues: #256 

Updated filter.py empty() function to explicitly check for the tag content being an instance of a DataElement instead of assuming it's a DataElement if it isn't a string.

Hi @vsoch!

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] My code follows the style guidelines of this project

# Open questions

None

### CODE REVIEW

**Comment by vsoch** [comment]
hey @wetzelj long time no see! I can definitely squash and merge - but is it maybe the case your master branch isn't in sync with upstream? The commit history is... intense!

**Comment by wetzelj** [comment]
It is.... but let me redo it tomorrow and clean it up.  I noticed that was... gross. :)

Hope you're doing well @vsoch! :)

**Comment by wetzelj** [comment]
Replacing with a new PR with a clean commit history

**Comment by wetzelj** [comment]
Replaced by #258

**Pull request closed without merging**
